In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [3]:
a[-1]

np.int64(4)

In [4]:
b=np.array([1,2,3,4,5,6,7,8,9])
b[0:9]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
b=np.array([1,2,3,4,5,6,7,8,9])
b[-1:5]

array([], dtype=int64)

In [8]:
c=b.copy()
c

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
b[0]=12
c

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
d=b.view()
d

array([12,  2,  3,  4,  5,  6,  7,  8,  9])

In [11]:
d

array([12,  2,  3,  4,  5,  6,  7,  8,  9])

In [12]:
a=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
b=a.reshape(4,3)
b

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [13]:
c=np.array([13,14,15])
d=np.concatenate((a,c))

In [14]:
np.array_split(d,2)

[array([1, 2, 3, 4, 5, 6, 7, 8]), array([ 9, 10, 11, 12, 13, 14, 15])]

In [15]:
np.where(d==4)

(array([3]),)

In [17]:
np.where(d%2==0)

(array([ 1,  3,  5,  7,  9, 11, 13]),)

In [18]:
c=np.array([[2,3,1,6],[5,1,2,4]])
np.sort(c)

array([[1, 2, 3, 6],
       [1, 2, 4, 5]])

In [19]:
c=np.array(['apple','orange','banana','mango'])
np.sort(c)

array(['apple', 'banana', 'mango', 'orange'], dtype='<U6')

In [20]:
np.random.rand(10)

array([0.64255628, 0.40578884, 0.59264986, 0.74668463, 0.67285589,
       0.54330837, 0.45146181, 0.94105671, 0.86333108, 0.08582111])

In [21]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [22]:
np.ones(2)

array([1., 1.])

In [23]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [24]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])